# https://docs.github.com/en/code-security/supply-chain-security/keeping-your-dependencies-updated-automatically/configuration-options-for-dependency-updates
version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    ignore:
      - dependency-name: "*"
        update-types: [ "version-update:semver-patch" ]
    groups:
      github-actions:
        patterns:
          - '*'

    commit-message:
      prefix: ci

  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: "weekly"
    ignore:
      - dependency-name: "org.yaml:snakeyaml"  # We want to stay on 1.14 to support as many versions of MC as possible
        versions: [ "version-update:semver-major" ]
    groups:
      packages:
        patterns:
          - '*'
